project_id = "dmikopljossmycwzyaxm"

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.detect-genre]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
